/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyCustomIconApp {
  MyCustomIconApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData maps_and_flags = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skewing_map = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deskewingmap = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_maps = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData license_plate = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indonesia = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData license_plate_8154394 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_stop_map = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
