// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKsaRTDsmOJK-8jNJ_8J3WCN0_HQt1Yww',
    appId: '1:97778600521:web:5c32d5406f2cd5e02b0d98',
    messagingSenderId: '97778600521',
    projectId: 'chat-app-e2eb8',
    authDomain: 'chat-app-e2eb8.firebaseapp.com',
    storageBucket: 'chat-app-e2eb8.firebasestorage.app',
    measurementId: 'G-4SKB0PJ141',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPJ-MaKYiZKfxlkkaNLh1WHZTpRXdCU_k',
    appId: '1:97778600521:android:f1a72013b4a543512b0d98',
    messagingSenderId: '97778600521',
    projectId: 'chat-app-e2eb8',
    storageBucket: 'chat-app-e2eb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgjB3gSxPmJOS_5L3eGO0FojZM1PTQZAc',
    appId: '1:97778600521:ios:6dac20f3499d17192b0d98',
    messagingSenderId: '97778600521',
    projectId: 'chat-app-e2eb8',
    storageBucket: 'chat-app-e2eb8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}