# analysis_options.yaml

# بيشمل قواعد النظافة البرمجية الرسمية من Flutter
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    missing_required_param: error
    missing_return: error
    unused_local_variable: warning
    todo: info
    invalid_assignment: error
    override_on_non_overriding_member: error

linter:
  rules:
  

    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_print
    - avoid_returning_null
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - null_closures
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - recursive_getters
    - slash_for_doc_comments
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_null_checks
    - use_key_in_widget_constructors
    - valid_regexps
